const data = {
  products: [
    {
      _id: '1',
      name: 'Matte Ceramic Subway Wall Tile',
      slug: 'signature-bianco-matte-ceramic-subway-wall-tile',
      category: 'Signature Tile',
      image: '/images/product1.jpg',
      price: 8.49,
      countInStock: 10,
      brand: 'Bianco',
      rating: 4.5,
      numReviews: 10,
      description: 'Matte subway wall tile - 4 x 8 in.',
    },
    {
      _id: '2',
      name: 'White Ceramic Wall Tile',
      slug: 'riad-white-ceramic-wall-tile',
      category: 'Bathroom Tile',
      image: '/images/product2.jpg',
      price: 12.69,
      countInStock: 0,
      brand: 'Riad',
      rating: 4.5,
      numReviews: 8,
      description: 'Moroccan-inspired white ceramic wall tile - 4 x 4 in.',
    },
    {
      _id: '3',
      name: 'Pearlescent Ceramic Wall Tile',
      slug: 'mallorca-pearlescent-ceramic-wall-tile',
      category: 'Fireplace Tile',
      image: '/images/product3.jpg',
      price: 11.79,
      countInStock: 10,
      brand: 'Mallorca',
      rating: 4.5,
      numReviews: 10,
      description: 'Pearlescent subway wall tile - 2.5 x 8 in.',
    },
    {
      _id: '4',
      name: 'Star Bone Porcelain Wall and Floor Tile',
      slug: 'kasbah-star-bone-porcelain-wall-and-floor-tile',
      category: 'Pool Tile',
      image: '/images/product4.jpg',
      price: 13.19,
      countInStock: 10,
      brand: 'Kasbah',
      rating: 4.5,
      numReviews: 10,
      description:
        'Moroccan Zellige porcelain wall and floor tile - 6.5 x 6.5 in.',
    },
  ],
};
export default data;
