const data = {
  products: [
    {
      _id: '1',
      name: 'Matte Ceramic Subway Wall Tile',
      slug: 'signature-bianco-matte-ceramic-subway-wall-tile',
      category: 'Signature Tile',
      image: '/images/product1.jpg',
      price: 8.49,
      countInStock: 9,
      brand: 'Bianco',
      rating: 4.5,
      numReviews: 10,
      description: 'Matte subway wall tile - 4 x 8 in.',
    },
    {
      _id: 'sample-1',
      name: '(Sample) Matte Ceramic Subway Wall Tile',
      slug: 'signature-bianco-matte-ceramic-subway-wall-tile-sample',
      category: 'Tile Samples',
      image: '/images/product1.jpg',
      price: 3.0,
      countInStock: 100, // Allow many samples
      brand: 'Bianco',
      rating: 4.0,
      numReviews: 12,
      description: 'Sample piece of the Matte Ceramic Subway Wall Tile.',
      isSample: true,
      isSampleOf: '1',
    },
    {
      _id: '2',
      name: 'White Ceramic Wall Tile',
      slug: 'riad-white-ceramic-wall-tile',
      category: 'Bathroom Tile',
      image: '/images/product2.jpg',
      price: 12.69,
      countInStock: 0,
      brand: 'Riad',
      rating: 4.5,
      numReviews: 8,
      description: 'Moroccan-inspired white ceramic wall tile - 4 x 4 in.',
    },
    {
      _id: 'sample-2',
      name: '(Sample) White Ceramic Wall Tile',
      slug: 'riad-white-ceramic-wall-tile-sample',
      category: 'Tile Samples',
      image: '/images/product2.jpg',
      price: 3.0,
      countInStock: 100, // Allow many samples
      brand: 'Riad',
      rating: 4.2,
      numReviews: 9,
      description: 'Sample piece of the White Ceramic Wall Tile.',
      isSample: true,
      isSampleOf: '2',
    },
    {
      _id: '3',
      name: 'Pearlescent Ceramic Wall Tile',
      slug: 'mallorca-pearlescent-ceramic-wall-tile',
      category: 'Fireplace Tile',
      image: '/images/product3.jpg',
      price: 11.79,
      countInStock: 10,
      brand: 'Mallorca',
      rating: 4.5,
      numReviews: 10,
      description: 'Pearlescent subway wall tile - 2.5 x 8 in.',
    },
    {
      _id: 'sample-3',
      name: '(Sample) Pearlescent Ceramic Wall Tile',
      slug: 'mallorca-pearlescent-ceramic-wall-tile-sample',
      category: 'Tile Samples',
      image: '/images/product3.jpg',
      price: 3.0,
      countInStock: 100, // Allow many samples
      brand: 'Mallorca',
      rating: 4.4,
      numReviews: 16,
      description: 'Sample piece of the Pearlescent Ceramic Wall Tile.',
      isSample: true,
      isSampleOf: '3',
    },
    {
      _id: '4',
      name: 'Star Bone Porcelain Wall and Floor Tile',
      sampleName: '(Sample)Pearlescent Ceramic Wall Tile',
      slug: 'kasbah-star-bone-porcelain-wall-and-floor-tile',
      category: 'Pool Tile',
      image: '/images/product4.jpg',
      price: 13.19,
      countInStock: 10,
      brand: 'Kasbah',
      rating: 4.5,
      numReviews: 10,
      description:
        'Moroccan Zellige porcelain wall and floor tile - 6.5 x 6.5 in.',
    },
    {
      _id: 'sample-4',
      name: '(Sample) Star Bone Porcelain Wall and Floor Tile',
      slug: 'kasbah-star-bone-porcelain-wall-and-floor-tile-sample',
      category: 'Tile Samples',
      image: '/images/product4.jpg',
      price: 3.0,
      countInStock: 100, // Allow many samples
      brand: 'Kasbah',
      rating: 4.1,
      numReviews: 11,
      description:
        'Sample piece of the Star Bone Porcelain Wall and Floor Tile.',
      isSample: true,
      isSampleOf: '4',
    },
  ],
};
export default data;
